name: Build and publish to Docker

on:
  workflow_dispatch:

env:
  # 设置 docker 镜像名
  IMAGE_NAME: tileserver-gl-light

jobs:
  build_postgis_docker_image:
    # needs: test
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - run: |  
          node publish.js --no-publish
          cd light
        working-directory: ./
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            scanlidocker/$IMAGE_NAME
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - 
      #   name: Get version # 获取 Tag Version
      #   id: vars
      #   run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: scanlidocker/tileserver-gl-light:v4.2.0
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
